let bcrypt = require("bcryptjs");
const moment = require("moment");
const data = {
  users: [
    {
      name: "Jesus",
      email: "jgomezbetancourt@outlook.com",
      password: bcrypt.hashSync("penco", 8),
      isadmin: "t",
      create_dt: moment().toDate(),
    },
    {
      name: "John",
      email: "john@outlook.com",
      password: bcrypt.hashSync("passwordsecret", 8),
      isadmin: "f",
      create_dt: moment().toDate(),
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      count_in_stock: 10,
      brand: "Nike",
      rating: 4.5,
      num_reviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      count_in_stock: 20,
      brand: "Adidas",
      rating: 4.0,
      num_reviews: 10,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      count_in_stock: 0,
      brand: "Lacoste",
      rating: 4.8,
      num_reviews: 17,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78.99,
      count_in_stock: 15,
      brand: "Nike",
      rating: 4.5,
      num_reviews: 14,
      description: "high quality product",
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      count_in_stock: 5,
      brand: "Puma",
      rating: 4.5,
      num_reviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      count_in_stock: 12,
      brand: "Adidas",
      rating: 4.5,
      num_reviews: 15,
      description: "high quality product",
    },
  ],
};
module.exports = data;
