version: "3.1"

services:
  db:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: pencopenco
      POSTGRES_USER: penco
      POSTGRES_DB: amazona

volumes:
  database-data:
